googleCloudStorage:
#  dataBucketName: europe-west2-mapaction-deve-542e8027-bucket
  dataBucketName: mapaction-pipeline-output-data
docker:
  imageName: eu.gcr.io/datapipeline-295515/mapaction-cloudcomposer-kubernetes-image
  imageVersion: v1.0.1
