required:
    - fclass
properties:
    geometry_type:
        items:
            enum:
                - MultiLineString
                - LineString
                - MultiLineString
        additionalItems: false
    crs:
        items:
            enum:
                - EPSG:4326
        additionalItems: false
