dirs:
  raw_data: raw_data
  processed_data: processed_data
  schemas: schemas

constants:
  crs: EPSG:4326

# Adding as empty values for now so that the DAGs don't break
hdx_cod:
  adm:
    address: null
    filename: null
    file_type: shp
    layer_name:
      adm0: null
      adm1: null
      adm2: null
      adm3: null
  roads:
    include: true
    address: null
    filename: null

adm_cod_raw: '{iso3}_cod_adm.zip'
adm0:
  schema: admin0_affected_area_py.yml
  cod:
    filename:
      category: admn
      theme: ad0
      geometry: py
      scale: s0
      source: unocha
      suffix: shp
    column_names:
      ADM0_EN: ADM0_EN
      ADM0_PCODE: ADM0_PCODE
adm1:
  schema: admin1_affected_area_py.yml
  cod:
    filename:
      category: admn
      theme: ad1
      geometry: py
      scale: s1
      source: unocha
      suffix: shp
    column_names:
      ADM1_EN: ADM1_EN
      ADM1_PCODE: ADM1_PCODE
      par_pcode: ADM0_PCODE
adm2:
  schema: admin2_affected_area_py.yml
  cod:
    filename:
      category: admn
      theme: ad2
      geometry: py
      scale: s2
      source: unocha
      suffix: shp
    column_names:
      ADM2_EN: ADM2_EN
      ADM2_PCODE: ADM2_PCODE
      par_pcode: ADM1_PCODE
adm3:
  schema: admin3_affected_area_py.yml
  cod:
    filename:
      category: admn
      theme: ad3
      geometry: py
      scale: s3
      source: unocha
      suffix: shp
    column_names:
      ADM3_EN: ADM3_EN
      ADM3_PCODE: ADM3_PCODE
      par_pcode: ADM2_PCODE


osm:
  url: 'http://overpass-api.de/api/interpreter?'
  roads:
    osm_tags: 'osm_tags_roads.yml'
    raw_xml: '{iso3}_osm_roads.xml'
    raw_gpkg: '{iso3}_osm_roads.gpkg'
    filename:
      category: tran
      theme: rds
      geometry: ln
      scale: s1
      source: osm
      suffix: shp
    column_names:
      name_en: 'name:en'
      name_loc: name
      fclass: highway
  rail:
    osm_tags: 'osm_tags_rail.yml'
    raw_xml: '{iso3}_osm_rail.xml'
    raw_gpkg: '{iso3}_osm_rail.gpkg'
    filename:
      category: tran
      theme: rrd
      geometry: ln
      scale: s1
      source: osm
      suffix: shp
    column_names:
      name_en: 'name:en'
      name_loc: name
      fclass: railway
  airports:
    osm_tags: 'osm_tags_airports.yml'
    raw_xml: '{iso3}_osm_airports.xml'
    raw_gpkg: '{iso3}_osm_airports.gpkg'
    filename:
      category: tran
      theme: air
      geometry: pt
      scale: s1
      source: osm
      suffix: shp
    column_names:
      name_en: 'name:en'
      name_loc: name
      fclass: aerodrome:type
  seaports:
    osm_tags: 'osm_tags_seaports.yml'
    raw_xml: '{iso3}_osm_seaports.xml'
    raw_gpkg: '{iso3}_osm_seaports.gpkg'
    filename:
      category: tran
      theme: por
      geometry: pt
      scale: s1
      source: osm
      suffix: shp
    column_names:
      name_en: 'name:en'
      name_loc: name
      fclass: port:type # no fclass?
  lakes:
    osm_tags: 'osm_tags_lakes.yml'
    raw_xml: '{iso3}_osm_lakes.xml'
    raw_gpkg: '{iso3}_osm_lakes.gpkg'
    filename:
      category: phys
      theme: lak
      geometry: py
      scale: s1
      source: osm
      suffix: shp
    column_names:
      name_en: 'name:en'
      name_loc: name
      fclass: water
  rivers:
    osm_tags: 'osm_tags_rivers.yml'
    raw_xml: '{iso3}_osm_rivers.xml'
    raw_gpkg: '{iso3}_osm_rivers.gpkg'
    filename:
      category: phys
      theme: riv
      geometry: ln
      scale: s1
      source: osm
      suffix: shp
    column_names:
      name_en: 'name:en'
      name_loc: name
      fclass: waterway
  seas:
    osm_tags: 'osm_tags_seas.yml'
    raw_xml: '{iso3}_osm_seas.xml'
    raw_gpkg: '{iso3}_osm_seas.gpkg'
    filename:
      category: phys
      theme: sea
      geometry: py
      scale: s0
      source: osm
      suffix: shp
    column_names:
      name_en: 'name:en'
      name_loc: name
      fclass: water
  places:
    osm_tags: 'osm_tags_places.yml'
    raw_xml: '{iso3}_osm_places.xml'
    raw_gpkg: '{iso3}_osm_places.gpkg'
    filename:
      category: stle
      theme: stl
      geometry: pt
      scale: s0
      source: osm
      suffix: shp
    column_names:
      name_en: 'name:en'
      name_loc: name
      fclass: place


roads_cod_raw: '{iso3}_cod_roads.zip'
roads:
  schema: roads_affected_area_ln.yml
  cod:
    # raw: '{iso3}_cod_roads.zip'
    filename:
      category: tran
      theme: rds
      geometry: ln
      scale: s1
      source: ocha
      suffix: shp
    column_names:
      name_en: null
      name_loc: null
      fclass: TYPE

srtm:
  altitude_light_deg: 315.0
  azimuth_light_deg: 45.0

geoboundaries:
  adm0:
    raw: 'geobnd_adm0.zip'
  adm1:
    raw: 'geobnd_adm1.zip'
  adm2:
    raw: 'geobnd_adm2.zip'
  adm3:
    raw: 'geobnd_adm3.zip'

gadm_layer:
  adm0: "gadm36_{ISO3}_0"
  adm1: "gadm36_{ISO3}_1"
  adm2: "gadm36_{ISO3}_2"
  adm3: "gadm36_{ISO3}_3"

cmf:
  top-level: GIS
  original:
    top-level: 1_Original_Data
  processed:
    top-level: 2_Active_Data
    adm0: 202_admn
    adm1: 202_admn
    adm2: 202_admn
    adm3: 202_admn
    roads: 232_tran
    rail: 232_tran
    airports: 232_tran
    seaports: 232_tran
    places: 229_stle
    rivers: 221_phys
    lakes: 221_phys
    seas: 221_phys
